const inteldata = {
  products: [
    {
      name: "intel-i3",
      id: 1,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i5",
      id: 2,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i7",
      id: 3,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i3",
      id: 4,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i5",
      id: 5,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i7",
      id: 6,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i3",
      id: 6,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i5",
      id: 7,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i7",
      id: 8,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i3",
      id: 9,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i5",
      id: 10,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/Intel/i3.jpg",
    },
    {
      name: "intel-i7",
      id: 11,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/Intel/i3.jpg",
    },
  ],
};
export default inteldata;
