const intelMotherBoardData = {
  motherboard: [
    {
      name: "intel-i3",
      id: 1,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "Supports 11th Gen Intel",
      Image: "/Images/Intel/b460m.jpg",
    },
    {
      name: "intel-i5",
      id: 2,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "Supports 11th Gen Intel",
      Image: "/Images/Intel/b560.jpg",
    },
    {
      name: "intel-i7",
      id: 3,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "Supports 11th Gen Intel",
      Image: "/Images/Intel/b560pro.jpg",
    },
    {
      name: "intel-i3",
      id: 4,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "Supports 12th Gen Intel",
      Image: "/Images/Intel/b560m.jpg",
    },
    {
      name: "intel-i5",
      id: 5,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "Supports 12th Gen Intel",
      Image: "/Images/Intel/b560pr.jpg",
    },
    {
      name: "intel-i7",
      id: 6,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "Supports 12th Gen Intel",
      Image: "/Images/Intel/b660.jpg",
    },
  ],
};
export default intelMotherBoardData;
