const AMDMotherBoardData = {
  motherboard: [
    {
      name: "ASRock A320M",
      id: 1,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "Supports 3rd Gen Ryzen",
      Image: "/Images/AMD/a320m.jpg",
    },
    {
      name: "ASRock A520M",
      id: 2,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "Supports 4rd Gen Ryzen",
      Image: "/Images/AMD/a520m.jpg",
    },
    {
      name: "Ryzen-7",
      id: 3,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "Supports 4rd Gen Ryzen",
      Image: "/Images/AMD/b450m.jpg",
    },
    {
      name: "Ryzen-3",
      id: 4,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "Supports 5rd Gen Ryzen",
      Image: "/Images/AMD/b550.jpg",
    },
    {
      name: "Ryzen-5",
      id: 5,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "Supports 5rd Gen Ryzen",
      Image: "/Images/AMD/b450mwifi.jpg",
    },
    {
      name: "Ryzen-7",
      id: 6,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "Supports 5rd Gen Ryzen",
      Image: "/Images/AMD/b550wowifi.jpg",
    },
  ],
};
export default AMDMotherBoardData;
