const AMDdata = {
  products: [
    {
      name: "Ryzen-3",
      id: 1,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/AMD/ryzen3.jpg",
    },
    {
      name: "Ryzen-5",
      id: 2,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/AMD/ryzen5.jpg",
    },
    {
      name: "Ryzen-7",
      id: 3,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/AMD/ryzen7.jpg",
    },
    {
      name: "Ryzen-3",
      id: 4,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/AMD/ryzen3.jpg",
    },
    {
      name: "Ryzen-5",
      id: 5,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/AMD/ryzen5.jpg",
    },
    {
      name: "Ryzen-7",
      id: 6,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/AMD/ryzen7.jpg",
    },
    {
      name: "Ryzen-3",
      id: 7,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/AMD/ryzen3.jpg",
    },
    {
      name: "Ryzen-5",
      id: 8,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/AMD/ryzen5.jpg",
    },
    {
      name: "Ryzen-7",
      id: 9,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/AMD/ryzen7.jpg",
    },
    {
      name: "Ryzen-3",
      id: 10,
      catergory: "processor",
      price: 3500,
      rating: 3.5,
      discription: "4 core 8 socket",
      Image: "/Images/AMD/ryzen3.jpg",
    },
    {
      name: "Ryzen-5",
      id: 11,
      catergory: "processor",
      price: 4500,
      rating: 4.5,
      discription: "6 core 12 socket",
      Image: "/Images/AMD/ryzen5.jpg",
    },
    {
      name: "Ryzen-7",
      id: 12,
      catergory: "processor",
      price: 5500,
      rating: 4,
      discription: "8 core 16 socket",
      Image: "/Images/AMD/ryzen7.jpg",
    },
  ],
};
export default AMDdata;
